//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authenticator.HttpModule.ServerCleanup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authenticator.HttpModule.ServerCleanup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAModule.
        /// </summary>
        internal static string Assemblyname {
            get {
                return ResourceManager.GetString("Assemblyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while removing module configuration from IIS server..
        /// </summary>
        internal static string ErrorPopupUnableToRemoveConfig {
            get {
                return ResourceManager.GetString("ErrorPopupUnableToRemoveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while removing module configuration from IIS server..
        /// </summary>
        internal static string ErrorPopupUnableToRemoveModuleApp {
            get {
                return ResourceManager.GetString("ErrorPopupUnableToRemoveModuleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while restarting server site. {0}.
        /// </summary>
        internal static string ErrorRestartServerSite {
            get {
                return ResourceManager.GetString("ErrorRestartServerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while restarting server site..
        /// </summary>
        internal static string ErrorRestartSite {
            get {
                return ResourceManager.GetString("ErrorRestartSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove module interface. {1}.
        /// </summary>
        internal static string ErrorUnableToRemoveInterface {
            get {
                return ResourceManager.GetString("ErrorUnableToRemoveInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove module from site {0} configuration with exception {1}..
        /// </summary>
        internal static string ErrorUnableToRemoveModule {
            get {
                return ResourceManager.GetString("ErrorUnableToRemoveModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing module configuration from IIS server.{0}.
        /// </summary>
        internal static string ErrorUnableToRemoveModuleConfig {
            get {
                return ResourceManager.GetString("ErrorUnableToRemoveModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpModule.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.webServer/modules.
        /// </summary>
        internal static string Modulesection {
            get {
                return ResourceManager.GetString("Modulesection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application present in site {0}..
        /// </summary>
        internal static string NoApplicationPresent {
            get {
                return ResourceManager.GetString("NoApplicationPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server site(s) configured with two factor authentication..
        /// </summary>
        internal static string NoServerSiteConfiguredWithfa {
            get {
                return ResourceManager.GetString("NoServerSiteConfiguredWithfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server site(s) registered in IIS..
        /// </summary>
        internal static string NoServerSiteRegistered {
            get {
                return ResourceManager.GetString("NoServerSiteRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Module Configuration.
        /// </summary>
        internal static string PopupMessageCaption {
            get {
                return ResourceManager.GetString("PopupMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed application {0} successfully..
        /// </summary>
        internal static string RemovedApplication {
            get {
                return ResourceManager.GetString("RemovedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed module element from {0} successfully..
        /// </summary>
        internal static string RemovedElementSuccess {
            get {
                return ResourceManager.GetString("RemovedElementSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting IIS server sites..
        /// </summary>
        internal static string RestartServerSite {
            get {
                return ResourceManager.GetString("RestartServerSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server sites restarted successfully..
        /// </summary>
        internal static string ServerSitesRestarted {
            get {
                return ResourceManager.GetString("ServerSitesRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server site {0} started successfully..
        /// </summary>
        internal static string ServerSiteStarted {
            get {
                return ResourceManager.GetString("ServerSiteStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server site {0} stopped successfully..
        /// </summary>
        internal static string ServerSiteStopped {
            get {
                return ResourceManager.GetString("ServerSiteStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unavailable..
        /// </summary>
        internal static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove module interface from site {0} with exception : {1}.
        /// </summary>
        internal static string UnableToRemoveModuleInterface {
            get {
                return ResourceManager.GetString("UnableToRemoveModuleInterface", resourceCulture);
            }
        }
    }
}
