//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authenticator.HttpModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authenticator.HttpModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Auth cookie data : {0}.
        /// </summary>
        internal static string AuthCookieData {
            get {
                return ResourceManager.GetString("AuthCookieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Auth cookie expired..
        /// </summary>
        internal static string AuthCookieExpired {
            get {
                return ResourceManager.GetString("AuthCookieExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Auth cookie is OK..
        /// </summary>
        internal static string AuthCookieOk {
            get {
                return ResourceManager.GetString("AuthCookieOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Refreshing auth cookie..
        /// </summary>
        internal static string AuthCookieRefresh {
            get {
                return ResourceManager.GetString("AuthCookieRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Checking Auth Cookie..
        /// </summary>
        internal static string CheckAuthCookie {
            get {
                return ResourceManager.GetString("CheckAuthCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthenticationRequest] Checking URL {0}.
        /// </summary>
        internal static string CheckingUrl {
            get {
                return ResourceManager.GetString("CheckingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Decrypt cookie .
        /// </summary>
        internal static string DecryptCookie {
            get {
                return ResourceManager.GetString("DecryptCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Decrypt cookie value : {0}.
        /// </summary>
        internal static string DecryptCookieValue {
            get {
                return ResourceManager.GetString("DecryptCookieValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Failed to refresh auth cookie..
        /// </summary>
        internal static string ErrorCookieRefresh {
            get {
                return ResourceManager.GetString("ErrorCookieRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Decryption of auth cookie failed..
        /// </summary>
        internal static string ErrorDecryptingCookieData {
            get {
                return ResourceManager.GetString("ErrorDecryptingCookieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Failed to extract auth cookie from request..
        /// </summary>
        internal static string ErrorReadingAuthCookie {
            get {
                return ResourceManager.GetString("ErrorReadingAuthCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Invalid auth cookie value : {0}.
        /// </summary>
        internal static string InvalidAuthCookiePresent {
            get {
                return ResourceManager.GetString("InvalidAuthCookiePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthenticationRequest] Is Url protected ? {0}.
        /// </summary>
        internal static string IsProtected {
            get {
                return ResourceManager.GetString("IsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log4net.config.
        /// </summary>
        internal static string Log4netConfigurationFileName {
            get {
                return ResourceManager.GetString("Log4netConfigurationFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAAuth.
        /// </summary>
        internal static string ModuleAuthCookieName {
            get {
                return ResourceManager.GetString("ModuleAuthCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdleTimeout.
        /// </summary>
        internal static string ModuleCookieIdleTimeout {
            get {
                return ResourceManager.GetString("ModuleCookieIdleTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FA.
        /// </summary>
        internal static string ModuleCookieValuePrefix {
            get {
                return ResourceManager.GetString("ModuleCookieValuePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /HttpModule.
        /// </summary>
        internal static string ModulePath {
            get {
                return ResourceManager.GetString("ModulePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestPath.
        /// </summary>
        internal static string ModuleRequestPathCookieName {
            get {
                return ResourceManager.GetString("ModuleRequestPathCookieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string ModuleResponseStatusDescription {
            get {
                return ResourceManager.GetString("ModuleResponseStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\HttpModule.Settings.xml.
        /// </summary>
        internal static string ModuleSettingFileName {
            get {
                return ResourceManager.GetString("ModuleSettingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] No auth cookie found in request..
        /// </summary>
        internal static string NoAuthCookiePresent {
            get {
                return ResourceManager.GetString("NoAuthCookiePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] No cookie in request..
        /// </summary>
        internal static string NoCookiePresent {
            get {
                return ResourceManager.GetString("NoCookiePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IssueAuthenticationChallenge] Redirect request to Authentication page..
        /// </summary>
        internal static string RedirectTo {
            get {
                return ResourceManager.GetString("RedirectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IssueAuthenticationChallenge] Rewrite Request..
        /// </summary>
        internal static string RewriteRequest {
            get {
                return ResourceManager.GetString("RewriteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CheckAuthCookie] Set cookie data : {0}.
        /// </summary>
        internal static string SetAuthCookieData {
            get {
                return ResourceManager.GetString("SetAuthCookieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IssueAuthenticationChallenge] Set redirect path : {0}.
        /// </summary>
        internal static string SetRequestPathCookie {
            get {
                return ResourceManager.GetString("SetRequestPathCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IssueAuthenticationChallenge] Set redirect path with querystring : {0}.
        /// </summary>
        internal static string SetRequestQueryString {
            get {
                return ResourceManager.GetString("SetRequestQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [RefreshCookie] Difference (in seconds.) of current and cookie set time : {0}.
        /// </summary>
        internal static string TimespanDifference {
            get {
                return ResourceManager.GetString("TimespanDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OnPostAcquireRequestState] URL is not protected..
        /// </summary>
        internal static string UnprotectedUrl {
            get {
                return ResourceManager.GetString("UnprotectedUrl", resourceCulture);
            }
        }
    }
}
